### ISSUE TITLE
[Bug]: ManagedPeripheral throws "Service not found" when device idle times out

### ISSUE THREAD

**Issue by gormster** [shinyorg/shiny#976]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [X] iOS 15
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [ ] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

1. Create an `IManagedPeripheral` with `CreateManaged()`
2. Listen for a notification on a given service characteristic using `WhenNotificationReceived()`. Make sure to subscribe to this with a long-lasting Disposable.
3. Enable notifications on that service characteristic using `EnableNotifications()`
4. Connect a BLE peripheral with an idle timeout feature.
5. Confirm that the notifications are working by getting the device to send some data on that service characteristic.
6. Wait for the device to idle timeout.

### Expected Behavior

The notification susbcription should not receive any more data, but nothing else should happen. When the device reconnects, I should be able to use the same ManagedPeripheral. (If that's not the case, it needs to be documented.) If the device never reconnects, holding a reference to the ManagedPeripheral should not cause any problems. (If I'm not supposed to hold a reference to it… well, that seems kind of weird.)

### Actual Behavior

The app crashes with an uncatchable exception "Service not found".

### Exception or Log output

```
System.ArgumentException: No service found - abf0
  at Shiny.BluetoothLE.Extensions+<>c__DisplayClass14_0.<Assert>b__0 (Shiny.BluetoothLE.IGattService service) [0x0001d] in <e43b4adcf32a4c0d84b7635abbd49337>:0
  at System.Reactive.Linq.ObservableImpl.Do`1+OnNext+_[TSource].OnNext (TSource value) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00000] in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServicesImpl.cs:19
  at System.Reactive.ExceptionHelpers.Throw (System.Exception exception) [0x00000] in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.cs:16
  at System.Reactive.Stubs+<>c.<.cctor>b__2_1 (System.Exception ex) [0x00000] in /_/Rx.NET/Source/src/System.Reactive/Internal/Stubs.cs:16
  at System.Reactive.AnonymousSafeObserver`1[T].OnError (System.Exception error) [0x00010] in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:62
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:60
  at at (wrapper other) System.Object.gsharedvt_out()
  at System.Reactive.Linq.ObservableImpl.Switch`1+_+InnerObserver[TSource].OnError (System.Exception error) [0x0002f] in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Switch.cs:114
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:60
  at at (wrapper other) System.Object.gsharedvt_out()
  at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:94
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Linq.ObservableImpl.Switch`1+_+InnerObserver[TSource].OnError (System.Exception error) [0x0002f] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Linq.ObservableImpl.Switch`1+_[TSource].OnError (System.Exception error) [0x00011] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Linq.ObservableImpl.Switch`1+_+InnerObserver[TSource].OnError (System.Exception error) [0x0002f] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Linq.ObservableImpl.Switch`1+_[TSource].OnError (System.Exception error) [0x00011] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Linq.ObservableImpl.Do`1+OnNext+_[TSource].OnNext (TSource value) [0x0000f] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.AutoDetachObserver`1[T].OnNextCore (T value) [0x00002] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.ObserverBase`1[T].OnNext (T value) [0x0000d] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at Shiny.RxExtensions.Respond[T] (System.IObserver`1[T] ob, T value) [0x00000] in <2c21bea6af72407c8a99514449798b35>:0
  at Shiny.BluetoothLE.Peripheral+<>c__DisplayClass16_1.<GetKnownService>b__1 (System.Object sender, Foundation.NSErrorEventArgs args) [0x0002f] in <e43b4adcf32a4c0d84b7635abbd49337>:0
  at CoreBluetooth.CBPeripheral+_CBPeripheralDelegate.DiscoveredService (CoreBluetooth.CBPeripheral peripheral, Foundation.NSError error) [0x00011] in /Users/builder/azdo/_work/2/s/xamarin-macios/src/build/ios/native/CoreBluetooth/CBPeripheral.g.cs:464
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.Type principalClass, System.Type delegateClass) [0x0003b] in /Users/builder/azdo/_work/2/s/xamarin-macios/src/UIKit/UIApplication.cs:85
  at ShinyPlayer.iOS.Application.Main (System.String[] args) [0x00001] in /Users/gormster/Projects/ShinyPlayer/ShinyPlayer.iOS/Main.cs:17
```

[Yes, my test app is called ShinyPlayer. It's a confusing name, but it was only created to diagnose this particular bug. Sorry.]

### Code Sample

NOTE: This is after much labour to try to fix this issue. The far simpler version I outlined in the steps to reproduce is where it started, and very much still triggers the bug.

```c#
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;
using Shiny;
using Shiny.BluetoothLE;
using Shiny.BluetoothLE.Managed;
using System.Reactive.Disposables;
using System.Reactive.Linq;

namespace ShinyPlayer
{
    public class MyPeripheral
    {
        public enum ConnectedState
        {
            Disconnected,
            Connecting,
            Connected
        }

        public readonly IManagedPeripheral Peripheral;
        public ConnectedState ConnectionState;
        public readonly CompositeDisposable DisposeWith;

        public MyPeripheral(IManagedPeripheral peripheral)
        {
            Peripheral = peripheral;
            ConnectionState = ConnectedState.Disconnected;
            DisposeWith = new CompositeDisposable();
        }
    }

    public partial class MainPage : ContentPage
    {

        private static string DATA_TRANSFER_SERVICE_UUID = "abf0";
        private static string DATA_TRANSFER_INPUT_CHARACTERISTIC_UUID = "abf2";
        private static string DATA_TRANSFER_OUTPUT_CHARACTERISTIC_UUID = "abf1";

        private CompositeDisposable scanDisposable = new CompositeDisposable();

        private IManagedScan scanner;

        private Dictionary<string, MyPeripheral> myPeripherals = new Dictionary<string, MyPeripheral>();

        public MainPage()
        {
            InitializeComponent();

            IBleManager bleManager = ShinyHost.Resolve<IBleManager>();

            ScanConfig scanConfig = new ScanConfig
            {
                ServiceUuids = { DATA_TRANSFER_SERVICE_UUID }
            };

            scanner = bleManager.CreateManagedScanner(scanConfig: scanConfig).DisposedBy(scanDisposable);

            scanner.WhenScan().SubscribeAsync(input => ScannerUpdate(input.Action, input.ScanResult)).DisposedBy(scanDisposable);
        }

        private async Task ScannerUpdate(ManagedScanListAction action, ManagedScanResult scanResult)
        {
            Console.WriteLine($"Scanner update {action} {scanResult.Name}");
            switch (action)
            {
                case ManagedScanListAction.Add:
                    await ConnectTalkiplayer(scanResult.Peripheral).ConfigureAwait(false);
                    break;
                case ManagedScanListAction.Update:
                    if (myPeripherals.ContainsKey(scanResult.Peripheral.Uuid))
                    {
                        var myPeripheral = myPeripherals[scanResult.Peripheral.Uuid];
                        if (myPeripheral.ConnectionState == MyPeripheral.ConnectedState.Connected
                            && !scanResult.IsConnected)
                        {
                            await myPeripheral.Peripheral.EnableNotifications(false, DATA_TRANSFER_SERVICE_UUID, DATA_TRANSFER_INPUT_CHARACTERISTIC_UUID);
                        }
                    }
                    break;
            }
        }

        private async Task ConnectTalkiplayer(IPeripheral peripheral)
        {
            Console.WriteLine($"Connecting to {peripheral.Name}");

            MyPeripheral myPeripheral;

            if (myPeripherals.ContainsKey(peripheral.Uuid))
            {
                myPeripheral = myPeripherals[peripheral.Uuid];
            }
            else
            {
                var managedPeripheral = peripheral.CreateManaged(System.Reactive.Concurrency.DefaultScheduler.Instance);
                myPeripheral = new MyPeripheral(managedPeripheral);
                myPeripheral.ConnectionState = MyPeripheral.ConnectedState.Connecting;

                myPeripherals.Add(peripheral.Uuid, myPeripheral);

                myPeripheral.Peripheral.WhenNotificationReceived(DATA_TRANSFER_SERVICE_UUID, DATA_TRANSFER_INPUT_CHARACTERISTIC_UUID)
                .Subscribe(bytes =>
                {
                    Device.BeginInvokeOnMainThread(() =>
                    {
                        Console.WriteLine($"Received {bytes.Length} bytes");
                        var message = MyPeripheralMessage.Decode(bytes);
                        Console.WriteLine(message.JsonData);
                    });
                }, (Exception ex) =>
                {
                    Console.Error.WriteLine(ex);
                })
                .DisposedBy(myPeripheral.DisposeWith);
            }

            await myPeripheral.Peripheral.EnableNotifications(true, DATA_TRANSFER_SERVICE_UUID, DATA_TRANSFER_INPUT_CHARACTERISTIC_UUID);

            Console.WriteLine($"Player connection status {myPeripheral.Peripheral.Status}");

            Console.WriteLine("Talkiplayer connected and awaiting notifications");
        }


        async void Button_Pressed(System.Object sender, System.EventArgs e)
        {

            if (scanner.IsScanning)
            {
                StartStopButton.Text = "Start scanning";
                scanner.Stop();
            }
            else
            {
                StartStopButton.Text = "Stop scanning";
                try
                {
                    await scanner.Start();
                } catch (Exception ex)
                {
                    Console.Error.Write(ex);
                }
            }
        }
    }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Please try the latest 2.5 preview.  There was an issue with serviceUUID detection that was fixed that should also resolve this.   

> (If that's not the case, it needs to be documented.)
Please recognize that this is not a product.  Stuff like this is not welcome here.

**Comment by gormster** [comment]
Can confirm that it still occurs with the 2.5 preview.

```
System.ArgumentException: No service found - abf0
  at Shiny.BluetoothLE.Extensions+<>c__DisplayClass14_0.<Assert>b__0 (Shiny.BluetoothLE.IGattService service) [0x0001d] in <c6cceeaa3784464698483346549c719e>:0
  at System.Reactive.Linq.ObservableImpl.Do`1+OnNext+_[TSource].OnNext (TSource value) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00000] in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServicesImpl.cs:19
  at System.Reactive.ExceptionHelpers.Throw (System.Exception exception) [0x00000] in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.cs:16
  at System.Reactive.Stubs+<>c.<.cctor>b__2_1 (System.Exception ex) [0x00000] in /_/Rx.NET/Source/src/System.Reactive/Internal/Stubs.cs:16
  at System.Reactive.AnonymousSafeObserver`1[T].OnError (System.Exception error) [0x00010] in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:62
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:60
  at at (wrapper other) System.Object.gsharedvt_out()
  at System.Reactive.Linq.ObservableImpl.Switch`1+_+InnerObserver[TSource].OnError (System.Exception error) [0x0002f] in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Switch.cs:114
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:60
  at at (wrapper other) System.Object.gsharedvt_out()
  at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:94
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Linq.ObservableImpl.Switch`1+_+InnerObserver[TSource].OnError (System.Exception error) [0x0002f] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Linq.ObservableImpl.Switch`1+_[TSource].OnError (System.Exception error) [0x00011] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Linq.ObservableImpl.Switch`1+_+InnerObserver[TSource].OnError (System.Exception error) [0x0002f] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Linq.ObservableImpl.Switch`1+_[TSource].OnError (System.Exception error) [0x00011] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.Linq.ObservableImpl.Do`1+OnNext+_[TSource].OnNext (TSource value) [0x0000f] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.AutoDetachObserver`1[T].OnNextCore (T value) [0x00002] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at System.Reactive.ObserverBase`1[T].OnNext (T value) [0x0000d] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
  at Shiny.RxExtensions.Respond[T] (System.IObserver`1[T] ob, T value) [0x00000] in <5dde96d40eae4f319b6cc666301698a6>:0
  at Shiny.BluetoothLE.Peripheral+<>c__DisplayClass16_1.<GetKnownService>b__1 (System.Object sender, Foundation.NSErrorEventArgs args) [0x0002f] in <c6cceeaa3784464698483346549c719e>:0
  at CoreBluetooth.CBPeripheral+_CBPeripheralDelegate.DiscoveredService (CoreBluetooth.CBPeripheral peripheral, Foundation.NSError error) [0x00011] in /Users/builder/azdo/_work/2/s/xamarin-macios/src/build/ios/native/CoreBluetooth/CBPeripheral.g.cs:464
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.Type principalClass, System.Type delegateClass) [0x0003b] in /Users/builder/azdo/_work/2/s/xamarin-macios/src/UIKit/UIApplication.cs:85
  at ShinyPlayer.iOS.Application.Main (System.String[] args) [0x00001] in /Users/gormster/Projects/ShinyPlayer/ShinyPlayer.iOS/Main.cs:17
```

> Please recognize that this is not a product. Stuff like this is not welcome here.

Sorry if this came across as a demand - it was not meant that way. This is an open-source project, and that comment was as much for myself as it was for any other contributor who wants to work on the docs for ManagedPeripheral. (I would like to write up some docs for it, but I'm worried about making incorrect assumptions.)

**Comment by gormster** [comment]
Unfortunately not, I don't have an Android phone to test on.

> The fact that this call succeeds after the initial connection but fails on a subsequent auto-reconnect is weird.

Oh, hang on – is it trying to automatically reconnect? The device has gone to sleep, it won't respond… maybe that's the problem.

*[Testing ensues]*

Yep! Setting `AutoConnect` to false prevents the issue from happening. I wonder if this is maybe specific to this hardware? It's an ESP32 using (afaik) the standard bluetooth stack, but I don't have the source code at hand.

And now I realise how this error is somehow escaping the reactive chain… it's [here](https://github.com/shinyorg/shiny/blob/a52b334a2e8167e3c33221e6182389f9352a1e5e/src/Shiny.BluetoothLE/Managed/ManagedPeripheral.cs#L40). When it attempts to automatically reconnect, the peripheral is offline, it doesn't advertise any services, so `GetKnownCharacteristic` throws an exception up the chain. But because this is an empty `Subscribe`, exceptions are unhandled, and just get thrown at the top level.

Not sure what the best fix is here: should `IManagedPeripheral` have a `WhenConnectionError` method? That seems kinda weird. Also, an error will trigger the end of the Observable sequence, so we'd need to re-establish the subscription whenever it errors out, but also make sure not to throw ourselves into an infinite loop…

Perhaps the oddest thing is that WhenConnected() is being called when the peripheral goes to sleep… AutoConnect tries to re-establish the connection, but apparently triggers WhenConnected even if the peripheral *isn't connected*… 

Oh, and another thing I found when trying to debug the issue: setting a breakpoint in `ManagedPeripheral.GetChar` *also* fixes the issue. Which indicates this is probably (sigh) a concurrency problem.

In any case, ManagedPeripheral shouldn't be throwing errors at the top level; its subscription handlers for `WhenConnected` and `WhenDisconnected` should handle exceptions in some way. The specifics of what's going wrong in this particular case probably don't matter.

**Comment by aritchie** [comment]
> But because this is an empty Subscribe, exceptions are unhandled, and just get thrown at the top level.
This is something I've had on the radar to fix for a while including a way to stop auto reconnects.  The goal of the managed peripheral was to take care of everything, but that needs some tweaking.

The fact that you aren't getting any services from the device, but it is allowing a connection is really weird.  It is a concurrency problem, but on the peripheral side.

**Comment by aritchie** [comment]
> Also, an error will trigger the end of the Observable sequence, so we'd need to re-establish the subscription whenever it errors out, but also make sure not to throw ourselves into an infinite loop…

Managed peripheral deals with resubscription.  It's actually one of its main usage points because people mess this up all the time.  The best way to do this, at least in terms of the exact use case since (imho) the peripheral is misbehaving, is to have the main observable error out (WhenNotificationReceived).  I had considered having an WhenErrorReceived but it would only trigger in two places.  The way I have "resubscription" also isn't the smartest solution anyhow.  I have a branch that is now attached to this issue that I'm going to rework how subscriptions & whennotificationreceived work.

**Comment by aritchie** [comment]
The issue of the error being thrown under the hood has been solved in the latest preview
